version: '2'
services:
    usersvc-app:
        image: usersvc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://usersvc-postgresql:5432/userSvc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    usersvc-postgresql:
        extends:
            file: postgresql.yml
            service: usersvc-postgresql
